
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

    jpa:
      database-platform: org.hibernate.dialect.MYSQL8InnoDBDialect
      open-in-view: false
      show-sql: true
      hibernate:
        format_sql: true
        ddl-auto: create


